### ISSUE TITLE
Documentation website broken

### ISSUE THREAD

**Issue by TheConnorJohnson** [sersoft-gmbh/swift-inotify#91]
I was looking to potentially use Swift-inotify for a project. However, the Github pages website is not working. 

[sersoft-gmbh.github.io/swift-inotify/](https://sersoft-gmbh.github.io/swift-inotify/)

Is there an alternative website I can use to find the documentation?

**Comment by ffried** [comment]
Huh, seems like Swift DocC's internal links have changed. The docs for v0.7.2 can be found at https://sersoft-gmbh.github.io/swift-inotify/0.7.2/documentation/inotify.
